USE [master]
GO

/****** Object:  Database [ONF_BlazorPOS_DEV]    Script Date: 2025-01-24 10:45:01 AM ******/
DROP DATABASE [ONF_BlazorPOS_DEV]
GO

/****** Object:  Database [ONF_BlazorPOS_DEV]    Script Date: 2025-01-24 10:45:01 AM ******/
CREATE DATABASE [ONF_BlazorPOS_DEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ONF_BlazorPOS_DEV', FILENAME = N'D:\1_ONF\ONF_Database\DB\ONF_BlazorPOS_DEV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlazorPOS_log', FILENAME = N'D:\1_ONF\ONF_Database\DB\ONF_BlazorPOS_DEV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ONF_BlazorPOS_DEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ARITHABORT OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET  MULTI_USER 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ONF_BlazorPOS_DEV] SET  READ_WRITE 
GO






